version: '3.3'

services:
        app:
                image: tmpimg

                deploy:
                        replicas: 3
                        resources:
                                limits:
                                        cpus: "0.1"
                                        memory: 50M
                        restart_policy:
                                condition: on-failure
                ports:
                        - 32000-32003:3000
