version: '3.3'

services:
        app:
                volumes:
                        - "active_storage:/app/storage"
                network_mode: bridge

                build:
                        context: .
                        dockerfile: Dockerfile
                deploy:
                        replicas: 3
                        resources:
                                limits:
                                        cpus: "0.2"
                                        memory: 50M
                        restart_policy:
                                condition: on-failure
                ports:
                        - 32000-32003:3000
volumes:
        active_storage:

