version: '3.3'

services:
        app:
                volumes:
                        - "active_storage:/app/storage"
                network_mode: bridge
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - 32000-32003:3000
volumes:
        active_storage:

